apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      enableServiceLinks: false
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
          - name: KAFKA_LISTENERS
            value: PLAINTEXT://0.0.0.0:29092
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka.nexus.svc.cluster.local:29092
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: PLAINTEXT:PLAINTEXT
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: nexus
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 29092
      targetPort: 29092
      protocol: TCP
  type: ClusterIP
