apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: "m******"
            - name: POSTGRES_USER
              value: "myu******"
            - name: POSTGRES_PASSWORD
              value: "********"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}  # ⚠️ Geçici veri (persist edilmez)
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: nexus
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
